name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.17.0+37

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  device_info_plus: ^4.0.1
  diffutil_dart: ^3.0.0
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  equatable: ^2.0.3
  fluentui_system_icons: ^1.1.177
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_displaymode: ^0.4.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_web_browser: ^0.17.1
  flutter_widget_from_html_core: ^0.8.5+3
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.0-dev.9
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  native_launcher:
    path: packages/native_launcher
  octo_image: ^1.0.2
  relative_time: ^2.0.1
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
