name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.0
  freezed_annotation: ^0.12.0
  dio: ^3.0.10
  uni_links: ^0.4.0
  flutter_widget_from_html_core: ^0.5.0+5
  url_launcher: ^5.7.2
  cached_network_image: ^2.3.2+1
  shimmer: ^1.1.1
  timeago: ^2.0.27
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.4
  share: ^0.6.5+2
  flutter_speed_dial:
    git:
      url: https://github.com/esieben1310/flutter_speed_dial
  html_unescape: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  flutter_launcher_icons:
    git:
      url: https://github.com/personalizedrefrigerator/flutter_launcher_icons

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
