name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.4.1+18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0-nullsafety
  dio: ^4.0.0-prev3
  fluentui_system_icons: ^1.1.110
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.0.0
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial
      ref: new
  flutter_widget_from_html_core: ^0.6.0-rc.2021031201
  hooks_riverpod: ^0.13.1+1
  html_unescape: ^2.0.0
  jiffy: ^4.0.0
  share: ^2.0.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  string_validator: ^0.3.0
  uni_links:
    git:
      url: https://github.com/objectivecosta/uni_links_simplified
  url_launcher: ^6.0.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.1+1
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
