name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.13.0+32

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  device_info_plus: ^3.1.1
  dio: ^4.0.3
  dio_smart_retry: ^1.0.3
  fluentui_system_icons: ^1.1.150
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.3
  flutter_displaymode: ^0.3.2
  flutter_hooks: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_speed_dial: ^4.6.6
  flutter_web_browser: ^0.15.0
  flutter_widget_from_html_core: ^0.8.2
  freezed_annotation: ^1.0.0
  hooks_riverpod: ^1.0.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.2
  intl: ^0.17.0
  jiffy:
    git:
      url: https://github.com/jama5262/jiffy
      ref: develop
  json_annotation: ^4.3.0
  native_launcher:
    path: packages/native_launcher
  octo_image: ^1.0.0+1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  string_validator: ^0.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.15

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.0.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
