name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.5.0+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  fluentui_system_icons: ^1.1.117
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.1.0
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial
      ref: new
  flutter_web_browser: ^0.14.0
  flutter_widget_from_html_core: ^0.6.0
  hooks_riverpod: ^0.14.0+1
  html_unescape: ^2.0.0
  jiffy: ^4.1.0
  native_launcher:
    path: packages/native_launcher
  share: ^2.0.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  string_validator: ^0.3.0
  uni_links2: ^0.6.0+2
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
