name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.1.2+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.5.0
  dio: ^3.0.10
  fluentui_system_icons: ^1.1.89
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  flutter_secure_storage: ^3.3.5
  flutter_speed_dial:
    git:
      url: https://github.com/esieben1310/flutter_speed_dial
  flutter_widget_from_html_core: ^0.5.1+4
  freezed_annotation: ^0.12.0
  hooks_riverpod: ^0.12.1
  html_unescape: ^1.0.2
  octo_image: ^0.3.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  timeago: ^2.0.29
  uni_links: ^0.4.0
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner: ^1.10.11
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.6
  json_serializable: ^3.5.1

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
