name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.8.0+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  fluentui_system_icons: ^1.1.135
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_displaymode: ^0.3.2
  flutter_hooks: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_speed_dial: ^4.2.0
  flutter_web_browser: ^0.15.0
  flutter_widget_from_html_core: ^0.6.1+4
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+4
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.17.0
  jiffy:
    git:
      url: https://github.com/jama5262/jiffy
      ref: develop
  native_launcher:
    path: packages/native_launcher
  octo_image: ^1.0.0+1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  string_validator: ^0.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.1
  freezed: ^0.14.2
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
